[package]
name = "pyum"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.0", features = ["mysql"] }
diesel_migrations = { version = "2.2.0", features = ["mysql"] }
dotenvy = "0.15"

axum = "0.7.5"
deadpool-diesel = { version = "0.4.1", features = ["mysql"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
