// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_footer from "./routes/_footer.tsx";
import * as $_head from "./routes/_head.tsx";
import * as $_header from "./routes/_header.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $_title from "./routes/_title.tsx";
import * as $admin_user_login_index from "./routes/admin_user/login/index.tsx";
import * as $admin_user_new_index from "./routes/admin_user/new/index.tsx";
import * as $device_detail_index from "./routes/device/detail/index.tsx";
import * as $device_edit_index from "./routes/device/edit/index.tsx";
import * as $device_index from "./routes/device/index.tsx";
import * as $device_new_index from "./routes/device/new/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_footer.tsx": $_footer,
    "./routes/_head.tsx": $_head,
    "./routes/_header.tsx": $_header,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/_title.tsx": $_title,
    "./routes/admin_user/login/index.tsx": $admin_user_login_index,
    "./routes/admin_user/new/index.tsx": $admin_user_new_index,
    "./routes/device/detail/index.tsx": $device_detail_index,
    "./routes/device/edit/index.tsx": $device_edit_index,
    "./routes/device/index.tsx": $device_index,
    "./routes/device/new/index.tsx": $device_new_index,
    "./routes/greet/[name].tsx": $greet_name_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
